device_no: 'single'
activation_instrument: cDAQ1Mod3
activation_channels: [8,10,13,11,7,12,14] # Channels through which voltages will be sent for activating the device (with both data inputs and control voltages)
min_activation_voltages: [-1.2, -1.2, -1.2, -1.2, -1.2, -0.7, -0.7]
max_activation_voltages: [0.6, 0.6, 0.6, 0.6, 0.6, 0.3, 0.3]
readout_instrument: cDAQ1Mod4
readout_channels: [2] # Channels for reading the output current values
trigger_source: cDAQ1/segment1
