device_no: 'multiple'
trigger_source: cDAQ1/segment1
A:
  activation_instrument: cDAQ1Mod2
  activation_channels: [6,0,7,5,2,4,3] #ao
  min_activation_voltages: [-1.2, -1.2, -1.2, -1.2, -1.2, -0.7, -0.7]
  max_activation_voltages: [0.7, 0.7, 0.7, 0.7, 0.7, 0.3, 0.3]
  activation_channel_mask: [1,1,1,1,1,1,1]
  readout_instrument: cDAQ1Mod4
  readout_channels: [0] # ai0
B:
  activation_instrument: cDAQ1Mod1
  activation_channels: [4,3,5,2,0,7,1] #ao
  min_activation_voltages: [-1.2, -1.2, -1.2, -1.2, -1.2, -0.7, -0.7]
  max_activation_voltages: [0.7, 0.7, 0.7, 0.7, 0.7, 0.3, 0.3]
  activation_channel_mask: [1,1,1,1,1,1,1]
  readout_instrument: cDAQ1Mod4
  readout_channels: [3] #ai3
C:
  readout_instrument: cDAQ1Mod4
  readout_channels: [2] #ai2
  activation_instrument: cDAQ1Mod3
  activation_channels: [14,7,13,8,10,11,12]
  min_activation_voltages: [-1.2, -1.2, -1.2, -1.2, -1.2, -0.7, -0.7]
  max_activation_voltages: [0.7, 0.7, 0.7, 0.7, 0.7, 0.3, 0.3]
  activation_channel_mask: [1,1,1,1,1,1,1]
D:
  activation_instrument: cDAQ1Mod3
  activation_channels: [0,2,5,3,4,6,1]
  min_activation_voltages: [-1.2, -1.2, -1.2, -1.2, -1.2, -0.7, -0.7]
  max_activation_voltages: [0.7, 0.7, 0.7, 0.7, 0.7, 0.3, 0.3]
  readout_instrument: cDAQ1Mod4
  readout_channels: [4] #ai4
  activation_channel_mask: [1,1,1,1,1,1,1]
E:
  activation_instrument: cDAQ1Mod1
  activation_channels: [10,13,9,14,8,15,11]
  min_activation_voltages: [-1.2, -1.2, -1.2, -1.2, -1.2, -0.7, -0.7]
  max_activation_voltages: [0.7, 0.7, 0.7, 0.7, 0.7, 0.3, 0.3]
  readout_instrument: cDAQ1Mod4
  readout_channels: [1] #cDAQ1Mod4/ai1
  activation_channel_mask: [1,1,1,1,1,1,1]
